apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/cb-kubecd/kubecon-golang3:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/cb-kubecd/kubecon-golang3:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: kubecon-golang3
        chartPath: charts/kubecon-golang3
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/cb-kubecd/kubecon-golang3"
          image.tag: "{{.DIGEST_HEX}}"
